### ISSUE TITLE
TODO-Liste

### ISSUE THREAD

**Issue by bronsen** [infuanfu/meta#10]
- [x] HST TIG200P Schweißgerät für Alu, Stahl, Edelstahl (hadez)
- [x] diverses Laborglas (hadez)
- [x] Prusa i3 MK2 3D Drucker (hadez)
- [x] Staubsauger (bronsen)
- [x] Wlan-foo (bronsen)
- [ ] Labeldrucker
- [ ] Gardinenstange für Banner
- [x] Isoprop
- [ ] Aceton
- [x] Wichstücher
- [x] Werkzeug
- [x] Zollstöcke
- [x] sowas wie Samlaboxen, aber in geil; besser vielleicht: Schütten
- [x] Arbeitstische
- [x] Arbeitsstühle
- [x] stabiles Regalsystem
- [x] Metallreflektorfolie für Fenster
- [x] Soundanlagen
- [x] Gerband
- [ ] ordentlicher Tesafilm
- [ ] Allestot für den Kühlschrank & dicke Putzhandschuhe
- [ ] Badreiniger
- [ ] Linoleumpflege
- [x] Putzeimer
- [x] Spiegelfolie
- [ ] Besen & Co zum saubermachen
- [ ] Ersatzschlösser für roten Schrank
- [ ] Deckenlampen überprüfen und in Betrieb nehmen
- [x] Cutter
- [x] einfaches Klebeband

**Comment by bronsen** [comment]
Fühlt euch frei, in dem Issue herumzueditieren!

Kann man ja vielleicht noch gruppieren oder so.
